    <div class="container-fluid">
      <div id="seventh-row" class="row text-center align-items-center justify-content-center">
        <div class="col-12">
          <a target="_blank" href="https://www.facebook.com/MUMentumUK"><div class="social-icon facebook"></div></a>
          <a target="_blank" href="https://meetu.ps/c/4ZlGs/Y8kD2/a"><div class="social-icon meetup"></div></a>
          <a target="_blank" href="https://instagram.com/mumentum_official"><div class="social-icon instagram"></div></a>
          <a target="_blank" href="https://www.linkedin.com/company/mumentum/"><div class="social-icon linkedin"></div></a>
        </div>
      </div>
    </div>

    <footer>
      <div id="footer" class="container-fluid">
        <div class="row align-items-center justify-content-center">
          <div class="col-sm-12 col-md-2 text-sm-center text-md-start">
            <span>&#169; Mumentum 2023</span>
          </div>
          <div class="col-sm-12 col-md-6 text-sm-center text-md-start">
            <span>Business Registered in England and Wales as MUMentum CIC: 14780046</span>
          </div>
          <div class="col-sm-12 col-md-4 text-sm-start text-md-end">
            <span><a href="/privacy policy.php">Privacy Policy</a></span>
            <span><a href="/terms and conditions.php">T&Cs</a></span>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/770f9fbc66.js" crossorigin="anonymous"></script>
  </footer>
</html>
