    <footer>
      <div id="footer" class="container-fluid">
        <div class="row">
          <div class="col-sm-6 text-left">
            <span>&#169; Mumentum 2023</span>
          </div>
          <div class="col-sm-6 text-end">
            <span><a href="/privacy policy.php">Privacy Policy</a></span>
            <span><a href="/terms and conditions.php">T&Cs</a></span>

            <!-- <a target="_blank" href="https://www.facebook.com/MUMentumUK"><i class="fa-right fa-brands fa-facebook"></i></a>
            <a target="_blank" href="https://instagram.com/mumentum_official?igshid=YmMyMTA2M2Y="><i class="fa-right fa-brands fa-instagram"></i></a>
            <a target="_blank" href="https://meetu.ps/c/4ZlGs/Y8kD2/a"><i class="fa-right fa-brands fa-meetup"></i></a>
            <a target="_blank" href="https://www.linkedin.com/company/mumentum/"><i class="fa-right fa-brands fa-linkedin-in"></i></a> -->
          </div>
        </div>
      </div>
    </footer>
  </body>
  <footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/770f9fbc66.js" crossorigin="anonymous"></script>
  </footer>
</html>
