    <footer>
      <div id="footer" class="container-fluid">
        <div class="row">
          <div class="col-sm-8 text-left">
            <span>&#169; Mumentum 2023</span>
            <span>Business Registered in England and Wales as MUMentum CIC: 14780046</span>
          </div>
          <div class="col-sm-4 text-end">
            <span><a href="/privacy policy.php">Privacy Policy</a></span>
            <span><a href="/terms and conditions.php">T&Cs</a></span>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/770f9fbc66.js" crossorigin="anonymous"></script>
  </footer>
</html>
