<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;700&family=Work+Sans:wght@100;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation&display=swap" rel="stylesheet">

    <title>MUMentum | Relax, Recharge and Reconnect</title>
    <link rel="icon" type="image/x-icon" href="/img/favicon-16x16.png">
    <link rel="stylesheet" href="/stylesheet.css">
  </head>
  <div class="sticky-top">
      <div class="container-fluid">
        <div class="row text-center events-header">
          <div class="col-sm-12">
            <p><a href="https://meetu.ps/c/4ZlGs/Y8kD2/a">View our upcoming events <i class="fa-solid fa-arrow-right-long"></i></a></p>
          </div>
        </div>
      </div>
    </div>
  <header class=""><!-- sticky-top -->
    <nav class="navbar navbar-expand-lg" id="heading-nav">
      <div id="nav-container" class="container-fluid">
        <a class="navbar-brand" href="/">
          <!-- <img id="logoImg" src="/imgs/mumentumLogo.png" alt=""> -->
          MUMentum</a>
        <button class="navbar-toggler ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fa-solid fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link navbar-mumentum" href="/about-us.php" role="button"> About Us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Socials
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="https://www.facebook.com/MUMentumUK">Facecook</a></li>
                <li><a class="dropdown-item" href="https://instagram.com/mumentum_official?igshid=YmMyMTA2M2Y=">Instagram</a></li>
                <li><a class="dropdown-item" href="https://meetu.ps/c/4ZlGs/Y8kD2/a">MeetUp</a></li>
                <li><a class="dropdown-item" href="https://www.linkedin.com/company/mumentum/">Linkedin</a></li>
              </ul>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link navbar-mumentum" href="/about-us.php" role="button"> Our MeetUps</a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>
